apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}-sabnzbd-cleanup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 2
      template:
        spec:
          automountServiceAccountToken: true
          restartPolicy: Never
          containers:
          - command:
            - /bin/sh
            - /script/script.sh
            image: alpine
            name: alpine
            volumeMounts:
            - mountPath: /script
              name: script
          volumes:
          - configMap:
              name: {{ .Release.Name }}-sabnzbd-cleanup
            name: script
  schedule: '@daily'
  successfulJobsHistoryLimit: 3
  suspend: false
