##
# bazarr
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bazarr
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-bazarr
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bazarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bazarr
    spec:
      containers:
      - name: bazarr
        image: "lscr.io/linuxserver/bazarr:{{ .Values.bazarr.version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6767
        # livenessProbe:
        #   httpGet:
        #     path: /bazarr/
        #     port: 6767
        # readinessProbe:
        #   httpGet:
        #     path: /bazarr/
        #     port: 6767
        env:
        - name: TZ
          value: Europe/Zurich
        volumeMounts:
        - name: {{ .Release.Name }}-bazarr
          mountPath: /config
        - name: {{ .Release.Name }}-library-tv
          mountPath: /tv
        - name: {{ .Release.Name }}-library-movies
          mountPath: /movies
      volumes:
        - name: {{ .Release.Name }}-library-tv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-library-tv
        - name: {{ .Release.Name }}-library-movies
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-library-movies
        - name: {{ .Release.Name }}-bazarr
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-bazarr
##
# landing page
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-homepage
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-homepage
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-homepage
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ .Release.Name }}-homepage
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: {{ .Release.Name }}-homepage
        configMap:
          name: {{ .Release.Name }}-homepage
          items:
            - key: index.html
              path: index.html

##
# nzbhydra
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nzbhydra2
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-nzbhydra2
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nzbhydra2
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nzbhydra2
    spec:
      containers:
      - name: nzbhydra
        image: "lscr.io/linuxserver/nzbhydra2:{{ .Values.nzbhydra2.version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5076
        # livenessProbe:
        #   httpGet:
        #     path: /nzbhydra2/
        #     port: 5076
        # readinessProbe:
        #   httpGet:
        #     path: /nzbhydra2/
        #     port: 5076
        env:
        - name: TZ
          value: Europe/Zurich
        volumeMounts:
        - name: {{ .Release.Name }}-nzbhydra2
          mountPath: /config
        - name: {{ .Release.Name }}-downloads
          mountPath: /downloads
      volumes:
        - name: {{ .Release.Name }}-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads
        - name: {{ .Release.Name }}-nzbhydra2
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-nzbhydra2

##
# oauth2 proxy for authenticated access
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}-oauth2-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-oauth2-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-oauth2-proxy
    spec:
      containers:
      # there seems to be a bug in 6+ keycloak provider which doesnt work well with jwt tokens
      # instead using the more standard oidc provider is required.
      # see: https://github.com/oauth2-proxy/oauth2-proxy/issues/773
      - args:
        # general config
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --upstream=file:///dev/null
        # pass auth headers
        - --pass-basic-auth=false
        - --pass-access-token=true
        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --skip-provider-button=true
        - --skip-auth-preflight=true
        - --pass-host-header=true
        # if jwt bearer token exists dont do a new authentication
        # but verify auth (e.g. for scripts)
        - --skip-jwt-bearer-tokens=true
        # auth0 configuration
        - --provider=oidc
        - --skip-oidc-discovery=false
        - --oidc-issuer-url=https://hutter-cloud.eu.auth0.com/
        - --scope=openid profile email

        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: cookie_secret
        image: "quay.io/oauth2-proxy/oauth2-proxy:{{ .Values.oauth2proxy.version }}"
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

##
# radarr
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-radarr
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-radarr
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-radarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-radarr
    spec:
      containers:
      - name: radarr
        image: "lscr.io/linuxserver/radarr:{{ .Values.radarr.version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7878
        # livenessProbe:
        #   httpGet:
        #     path: /radarr/
        #     port: 7878
        # readinessProbe:
        #   httpGet:
        #     path: /radarr/
        #     port: 7878
        env:
        - name: TZ
          value: Europe/Zurich
        # sabznbd needs to run as root to allow loopback mounts
        # of iso images. as sabnzbd writes wiles with root ownership
        # radarr and sonarr need to run as root too to allow move
        # of the downloaded files to plex
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - name: {{ .Release.Name }}-radarr
          mountPath: /config
        - name: {{ .Release.Name }}-library-movies
          mountPath: /movies
        - name: {{ .Release.Name }}-downloads
          mountPath: /downloads
      volumes:
        - name: {{ .Release.Name }}-library-movies
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-library-movies
        - name: {{ .Release.Name }}-radarr
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-radarr
        - name: {{ .Release.Name }}-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads
##
# sabnzbd container
# deploy sabnzbd container
# to remove the need for a custom container
# the container installs nzbtomedia and its requirements
# during container startup
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sabnzbd
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-sabnzbd
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sabnzbd
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sabnzbd
    spec:
      initContainers:
      - name: nzbtomedia
        image: "lscr.io/linuxserver/sabnzbd:{{ .Values.sabnzbd.version }}"
        command:
          - /bin/sh
          - /script/script.sh
        volumeMounts:
        - name: {{ .Release.Name }}-nzbtomedia-init
          mountPath: /script
        - name: {{ .Release.Name }}-nzbtomedia
          mountPath: /nzbtomedia
        - name: {{ .Release.Name }}-downloads
          mountPath: /downloads
        - name: {{ .Release.Name }}-incomplete-downloads
          mountPath: /incomplete-downloads
      containers:
      - name: sabnzbd
        image: "lscr.io/linuxserver/sabnzbd:{{ .Values.sabnzbd.version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        env:
        - name: TZ
          value: Europe/Zurich
        # sabznbd needs to run as root to allow loopback mounts
        # of iso images
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - name: {{ .Release.Name }}-sabnzbd
          mountPath: /config
        - name: {{ .Release.Name }}-downloads
          mountPath: /downloads
        - name: {{ .Release.Name }}-incomplete-downloads
          mountPath: /incomplete-downloads
        - name: {{ .Release.Name }}-nzbtomedia
          mountPath: /nzbToMedia
          subPath: nzbToMedia
        command:
        - /bin/sh
        - -c
        - "apk add --no-cache ffmpeg git && exec /init"
        securityContext:
          privileged: true
      volumes:
        - name: {{ .Release.Name }}-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads
        - name: {{ .Release.Name }}-incomplete-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-incomplete-downloads
        - name: {{ .Release.Name }}-sabnzbd
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-sabnzbd
        - name: {{ .Release.Name }}-nzbtomedia
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-nzbtomedia
        - name: {{ .Release.Name }}-nzbtomedia-init
          configMap:
            name: {{ .Release.Name }}-nzbtomedia-init

##
# sonarr
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sonarr
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-sonarr
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sonarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sonarr
    spec:
      containers:
      - name: sonarr
        image: "lscr.io/linuxserver/sonarr:{{ .Values.sonarr.version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8989
        # livenessProbe:
        #   httpGet:
        #     path: /sonarr/
        #     port: 8989
        # readinessProbe:
        #   httpGet:
        #     path: /sonarr/
        #     port: 8989
        env:
        - name: TZ
          value: Europe/Zurich
        # sabznbd needs to run as root to allow loopback mounts
        # of iso images. as sabnzbd writes wiles with root ownership
        # radarr and sonarr need to run as root too to allow move
        # of the downloaded files to plex
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - name: {{ .Release.Name }}-sonarr
          mountPath: /config
        - name: {{ .Release.Name }}-library-tv
          mountPath: /tv
        - name: {{ .Release.Name }}-downloads
          mountPath: /downloads
      volumes:
        - name: {{ .Release.Name }}-library-tv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-library-tv
        - name: {{ .Release.Name }}-sonarr
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-sonarr
        - name: {{ .Release.Name }}-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads

##
# file browser
##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-file-browser
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-file-browser
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-file-browser
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-file-browser
    spec:
      containers:
      - name: filebrowser
        image: "filebrowser/filebrowser:{{ .Values.filebrowser.version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        command:
        - /filebrowser
        - --port
        - "80"
        - --disable-exec
        - --noauth
        - --baseurl
        - /browser
        volumeMounts:
        - name: {{ .Release.Name }}-downloads
          mountPath: /srv/downloads
        - name: {{ .Release.Name }}-library-tv
          mountPath: /srv/library/tv
        - name: {{ .Release.Name }}-library-movies
          mountPath: /srv/library/movies
        - name: {{ .Release.Name }}-library-audiobooks
          mountPath: /srv/library/audiobooks
      volumes:
        - name: {{ .Release.Name }}-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads
        - name: {{ .Release.Name }}-library-tv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-library-tv
        - name: {{ .Release.Name }}-library-movies
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-library-movies
        - name: {{ .Release.Name }}-library-audiobooks
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-library-audiobooks
