# nfs volumes to access shared media library
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-library-movies
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Release.Name }}-library-movies
  accessModes: [ReadWriteMany]
  capacity: { storage: 1Gi }
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.library.base_path }}/movies
    server: {{ .Values.library.nfs_server }}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-library-tv
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Release.Name }}-library-tv
  accessModes: [ReadWriteMany]
  capacity: { storage: 1Gi }
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.library.base_path }}/tv
    server: {{ .Values.library.nfs_server }}
    readOnly: false
