# Default values for node-a.

# storage class name for local volumes
storage_class_name: persistent

# library nfs storage configuration
library:
  nfs_server: 192.168.30.17
  base_path: /volume1/library
