---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # hardcoded for easier reference
  name: grafana-admin-credentials
spec:
  data:
  - remoteRef:
      key: hutter-cloud-grafana-admin-password
    secretKey: adminPassword
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        admin-user: admin
        admin-password: {{ printf "'{{ .adminPassword }}'" }}
      engineVersion: v2
