# create externalname service to allow ext-dns
# to create a cname record

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-arg-grafana-extname
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana-rqarg.hutter.cloud
    hutter.cloud/dns-service: "aws"
spec:
  type: ExternalName
  externalName: infra.hutter.cloud
