---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: {{ .Release.Name }}-grafana
