
externalName:
  enabled: true

externalSecret:
  enabled: true

adminClusterRoleBinding:
  enabled: true

jenkins:
  controller:
    jenkinsAdminEmail: huttersebastian@gmail.com
    jenkinsUrlProtocol: https
    additionalPlugins:
    - oic-auth
    - plasticscm-plugin
    - dotnet-sdk
    - kubernetes-credentials-provider
    - matrix-auth
    additionalExistingSecrets:
    - name: jenkins-auth0-client
      keyName: clientId
    - name: jenkins-auth0-client
      keyName: clientSecret
    JCasC:
      securityRealm: |-
        oic:
          authorizationServerUrl: "https://hutter-cloud.eu.auth0.com/authorize"
          automanualconfigure: "auto"
          clientId: "${jenkins-auth0-client-clientId}"
          clientSecret: "${jenkins-auth0-client-clientSecret}"
          disableSslVerification: false
          emailFieldName: "email"
          fullNameFieldName: "name"
          logoutFromOpenidProvider: false
          overrideScopes: "openid email profile"
          overrideScopesDefined: true
          scopes: "openid profile email"
          tokenAuthMethod: "client_secret_post"
          tokenServerUrl: "https://hutter-cloud.eu.auth0.com/oauth/token"
          userInfoServerUrl: "https://hutter-cloud.eu.auth0.com/userinfo"
          userNameField: "email"
          wellKnownOpenIDConfigurationUrl: "https://hutter-cloud.eu.auth0.com/.well-known/openid-configuration"
    ingress:
      enabled: true
      apiVersion: networking.k8s.io/v1
      hostName: jenkins.hutter.cloud
      annotations:
        kubernetes.io/ingress.class: public
        cert-manager.io/cluster-issuer: letsencrypt-dns
      tls:
      - hosts: ["jenkins.hutter.cloud"]
        secretName: jenkins-tls
  persistence:
    storageClass: persistent
    accessMode: ReadWriteMany
