apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.applicationPrefix }}-overseerr
  namespace: default
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: git@github.com:huttercloud/applications.git
    targetRevision: HEAD
    path: charts/overseerr
    helm:
      releaseName: overseerr
      valueFiles:
        - {{ .Values.spec.valuesFile }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
