apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.2.2
    chart: prometheus
    helm:
      releaseName: prometheus
      valueFiles:
        - prometheus-values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
