apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: git@github.com:huttercloud/applications.git
    targetRevision: HEAD
    path: charts/prometheus
    helm:
      releaseName: prometheus
      valueFiles:
        - values-node-b.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
