apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usenet
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:huttercloud/applications.git
    targetRevision: HEAD
    path: charts/usenet
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default