apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # no prefix added here as pvcs with configuration are already in place!
  name: usenet
  namespace: default
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: git@github.com:huttercloud/applications.git
    targetRevision: HEAD
    path: charts/usenet
    helm:
      parameters:
        - name: ingress.host
          value: usenet.hutter.cloud
        # versions for usenet services
        # values defined as single line to allow github action to auto update versions
        - { name: sabnzbd.version, value: 3.7.1 }
        - { name: nzbtomedia.version, value: 12.1.10 }
        - { name: oauth2proxy.version, value: v7.4.0 }
        - { name: nzbhydra2.version, value: 4.7.6 }
        - { name: filebrowser.version, value: v2.23.0 }
        - { name: sonarr.version, value: 3.0.9 }
        - { name: radarr.version, value: 4.2.4 }
        - { name: bazarr.version, value: 1.1.4 }

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
