apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usenet
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:huttercloud/applications.git
    targetRevision: HEAD
    path: charts/usenet
    helm:
      parameters:
        - name: ingress.host
          value: usenet-2.hutter.cloud
        # versions for sabnzbd image and helper functions
        - name: sabnzbd.version
          value: 3.7.1
        - name: nzbtomedia.version
          value: 12.1.10

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default