
externalName:
  enabled: true

oauth2:
  enabled: true
  # single line oauth2 proxy version for update-versions script
  proxy: { version: "v7.4.0" }

prometheus:
  # enable all dependencies
  prometheus-node-exporter:
    enabled: true
  alertmanager:
    enabled: true
  kube-state-metrics:
    enabled: true
  prometheus-pushgateway:
    enabled: true
  # setup prometheus server with persistence and ingress
  server:
    baseUrl: prometheus.hutter.cloud
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
        kubernetes.io/ingress.class: public
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      hosts:
        - prometheus.hutter.cloud
      tls:
        - secretName: prometheus-server-tls
          hosts:
            - prometheus.hutter.cloud
    persistentVolume:
      accessMOdes:
        - ReadWriteMany
      storageClass: persistent-2
  # add scraping targets for nodes outside the cluster
  extraScrapeConfigs: |
    - job_name: "node-c-node-exporter"
      metrics_path: /metrics
      scheme: http
      honor_lables: true
      static_configs:
        - targets:
          - node-c.hutter.cloud:9100
