{{- if .Values.federateService.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-federate-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 9090
  selector:
    app: prometheus
    component: server
    release: {{ .Release.Name }}
{{- end }}
