---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-freshrss
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    kubernetes.io/ingress.class: public
spec:
  tls:
    - hosts: [{{ .Values.ingress.freshrss }}]
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.ingress.freshrss }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-freshrss
              port:
                number: 80
