---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-freshrss
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-freshrss
