apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-12T07:14:28Z"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
data:
  script.sh: |
    #!/bin/sh
    set -e

    pip install --upgrade pip
    pip install paramiko scp

    exec python3 /script/synology-certificate.py  upsert.json: |
    
  synology-certificate.py: |
    {{ .Files.Get "synology-certificate.py" | nindent 4 }}