apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  data:
  - remoteRef:
      key: hutter-cloud-service-synology-certificate-private-key
    secretKey: privatekey
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        private-key: {{ printf "'{{ .privatekey }}'" }}
      engineVersion: v2
