apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
data:
  init.sh: |
    #!/bin/sh
    set -e

    apt-get update
    # placeholder
    apt-get install -y nginx
    nginx -g 'daemon off;'

  authenticate.py: |
    {{ .Files.Get "authenticate.py" | nindent 4 }}
