apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
data:
  init.sh: |
    #!/bin/sh
    set -e

    apt-get update
    apt-get install -y python3 python3-pip pure-ftpd rsyslog
    pip install --upgrade requests email-validator

    cat /certificate/tls.key /certificate/tls.crt  > /etc/ssl/private/pure-ftpd.pem
    chmod 600 /etc/ssl/private/pure-ftpd.pem

    # create user and group
    groupadd -g 999 ftp
    useradd -M -u 999 -g 999 ftp

    # start rsyslogd
    rsyslogd

    # start authd daemon
    /usr/sbin/pure-authd \
        --run /authenticate.py \
        --socket /var/run/ftpd.sock \
        --daemonize

    # start pure ftpd daemon
    /usr/sbin/pure-ftpd \
        --tls=1 \
        --dontresolve \
        --passiveportrange 30000:30009 \
        --maxclientsnumber 5 \
        --maxclientsperip 5 \
        --noanonymous \
        --nochmod \
        --antiwarez \
        --forcepassiveip 192.168.30.90 \
        -lextauth:/var/run/ftpd.sock \
        --daemonize

    # tail messages
    tail -F /var/log/messages

  authenticate.py: |
{{ .Files.Get "authenticate.py" | trim | indent 4 }}
