apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  data:
  - remoteRef:
      key: hutter-cloud-service-pureftpd-client-id
    secretKey: clientId
  - remoteRef:
      key: hutter-cloud-service-pureftpd-client-secret
    secretKey: clientSecret
  - remoteRef:
      key: hutter-cloud-service-pureftpd-audience
    secretKey: audience
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        clientId: {{ printf "'{{ .clientId }}'" }}
        clientSecret: {{ printf "'{{ .clientSecret }}'" }}
        audience: {{ printf "'{{ .audience }}'" }}
      engineVersion: v2
