---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
#   - name: ftpc
#     port: 20
#     protocol: TCP
#     targetPort: 20
#     nodePort: 20
  - name: ftp
    port: 21
    protocol: TCP
    targetPort: 21
    nodePort: 21
  {{- range untilStep 30000 30009 1 }}
  - port: {{ . }}
    targetPort: {{ . }}
    protocol: TCP
    name: "ftpa-{{ . }}"
    nodePort: {{ . }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-pureftpd
