
externalName:
  enabled: true

externalSecret:
  enabled: true

loki:
  # disable chart dependencies
  minio:
    enabled: false
  monitoring:
    selfMonitoring:
      grafanaAgent:
        installOperator: false
  loki:
    # enable single binary deployment (one loki pod doin everyghin!)
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem
    auth_enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
  singleBinary:
    persistence:
      storageClass: persistent-2
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      kubernetes.io/ingress.class: public
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: loki-gateway-basic-auth
      nginx.ingress.kubernetes.io/auth-secret-type: auth-file
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        proxy_set_header X-Scope-OrgID $remote_user;
        satisfy any;
        allow 192.168.30.0/24;
        deny all;
    hosts:
      - loki.hutter.cloud
    tls:
      - secretName: loki-gateway-tls
        hosts:
          - loki.hutter.cloud
  # disable gateway - even though it's not really used
  # in single bin deployments
  gateway:
    enabled: false
