apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: default
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: git@github.com:huttercloud/applications.git
    targetRevision: HEAD
    path: charts/hello-world
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
