# store tatulli config and stats
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.storage_class_name }}
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 1Gi } }
