apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-12T07:14:28Z"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
data:
  script.sh: |
    #!/bin/sh
    set -e

    public_ip=$(curl --silent ifconfig.co)
    [ -z "${public_ip}" ] && echo unable to retrieve ip, aborting. && exit 1
    echo upsert entry for home.hutter.cloud to $public_ip
    sed "s/IPADDRESS/${public_ip}/g" /script/upsert.json > /tmp/upsert.json

    aws route53 change-resource-record-sets --hosted-zone-id ${HOSTED_ZONE_ID} --change-batch file:///tmp/upsert.json
  upsert.json: |
    {
      "Comment": "Set public ip",
      "Changes": [
        {
          "Action": "UPSERT",
          "ResourceRecordSet": {
            "Name":  "{{ .Values.public_name }}",
            "Type": "A",
            "TTL": 300,
            "ResourceRecords": [
              {
                "Value": "IPADDRESS"
              }
            ]
          }
        }
      ]
    }