apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  data:
  - remoteRef:
      key: hutter-cloud-dns-zone-id
    secretKey: zoneid
  - remoteRef:
      key: hutter-cloud-dns-access-key-id
    secretKey: accesskey
  - remoteRef:
      key: hutter-cloud-dns-secret-access-key
    secretKey: secretkey
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        accessKey: {{ printf "'{{ .accesskey }}'" }}
        secretKey: {{ printf "'{{ .secretkey }}'" }}
        zoneId: {{ printf "'{{ .zoneid }}'" }}
      engineVersion: v2
