---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    # if ingress alias is set then add it to the ingress
    {{- if .Values.ingress.alias }}
    nginx.ingress.kubernetes.io/server-alias: {{ .Values.ingress.alias }}
    {{- end }}
    kubernetes.io/ingress.class: public
spec:
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 80
