---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-opds-basic-auth
spec:
  data:
  - remoteRef:
      key: hutter-cloud-calibre-opds-credentials
    secretKey: htpasswd
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        auth: {{ printf "'{{ .htpasswd }}'" }}
      engineVersion: v2
