#
# setup {{ .Values.storage_class_name }} volume claims for all services
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-calibre
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.storage_class_name }}
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-calibre-web
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.storage_class_name }}
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-library-ebooks
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Release.Name }}-library-ebooks
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 1Gi } }
