# nfs volumes to access shared media library
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-library-ebooks
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Release.Name }}-library-ebooks
  accessModes: [ReadWriteMany]
  capacity: { storage: 1Gi }
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/ebooks
    server: {{ .Values.library.nfs_server }}
    readOnly: false
