---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-external-name-synology
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "synology.hutter.cloud"
    hutter.cloud/dns-service: "aws"
spec:
  type: ExternalName
  externalName: infra.hutter.cloud

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-external-name-nfs
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "nfs.hutter.cloud"
    hutter.cloud/dns-service: "aws"
spec:
  type: ExternalName
  externalName: infra.hutter.cloud
