---
#
# this workflow "updates" software versions for node-a and node-b
#

name: "update-versions"

on:
  # allow for manual execution
  workflow_dispatch:
  # run once a week
  schedule:
    - cron: '0 3 * * 1'

permissions: write-all

env:
  WORDPRESS_SFTP_PASSWORD: ${{ secrets.WORDPRESS_COM_SFTP_PASSWORD }}

jobs:
  update-versions:
    name: "Update local versions"
    runs-on: "ubuntu-latest"
    permissions: write-all

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          path: applications

      - name: "Checkout update-versions repository"
        uses: actions/checkout@v3
        with:
          path: update-versions
          repository: huttercloud/update-versions
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update-versions/requirements.txt
      - name: Update versions
        run: |
          python3 update-versions/update-versions.py \
            --file applications/applications/node-b/templates/usenet.yaml \
            --replace '\s*?-\s{\sname:\s+sabnzbd.version,\svalue:\s(.*)\s}' SABNZBD \
            --replace '\s*?-\s{\sname:\s+nzbtomedia.version,\svalue:\s(.*)\s}' NZBTOMEDIA \
            --replace '\s*?-\s{\sname:\s+oauth2proxy.version,\svalue:\s(.*)\s}' OAUTH2PROXY \
            --replace '\s*?-\s{\sname:\s+nzbhydra2.version,\svalue:\s(.*)\s}' NZBHYDRA2 \
            --replace '\s*?-\s{\sname:\s+filebrowser.version,\svalue:\s(.*)\s}' FILEBROWSER \
            --replace '\s*?-\s{\sname:\s+sonarr.version,\svalue:\s(.*)\s}' SONARR \
            --replace '\s*?-\s{\sname:\s+radarr.version,\svalue:\s(.*)\s}' RADARR \
            --replace '\s*?-\s{\sname:\s+bazarr.version,\svalue:\s(.*)\s}' BAZARR

          python3 update-versions/update-versions.py \
            --file applications/applications/node-b/templates/prometheus.yaml \
            --replace '\s*?targetRevision:\s(.*)' PROMETHEUS
      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        with:
          path: applications
          commit-message: "chore(update): Update versions"
          branch: "chore/update-versions-${{ steps.date.outputs.date }}"
          delete-branch: true
          title: "chore: Update versions ${{ steps.date.outputs.date }}"
          reviewers: |
            sebastianhutter
