---
#
# this workflow "updates" software versions for node-a and node-b
#

name: "update-versions"

on:
  # allow for manual execution
  workflow_dispatch:
  # run once a week
  schedule:
    - cron: '0 3 * * 1'

permissions: write-all

env:
  WORDPRESS_SFTP_PASSWORD: ${{ secrets.WORDPRESS_COM_SFTP_PASSWORD }}

jobs:
  update-versions:
    name: "Update local versions"
    runs-on: "ubuntu-latest"
    permissions: write-all

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          path: applications

      - name: "Checkout update-versions repository"
        uses: actions/checkout@v3
        with:
          path: update-versions
          repository: huttercloud/update-versions
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update-versions/requirements.txt
      - name: Update versions
        run: |
          python3 update-versions/update-versions.py \
            --file applications/charts/usenet/values-node-b.yaml \
            --replace 'sabnzbd:\s{\sversion:\s\"(.*)\"\s}' SABNZBD \
            --replace 'nzbtomedia:\s{\sversion:\s\"(.*)\"\s}' NZBTOMEDIA \
            --replace 'oauth2proxy:\s{\sversion:\s\"(.*)\"\s}' OAUTH2PROXY \
            --replace 'nzbhydra2:\s{\sversion:\s\"(.*)\"\s}' NZBHYDRA2 \
            --replace 'filebrowser:\s{\sversion:\s\"(.*)\"\s}' FILEBROWSER \
            --replace 'sonarr:\s{\sversion:\s\"(.*)\"\s}' SONARR \
            --replace 'radarr:\s{\sversion:\s\"(.*)\"\s}' RADARR \
            --replace 'bazarr:\s{\sversion:\s\"(.*)\"\s}' BAZARR \
            --replace 'readarr:\s{\sversion:\s\"(.*)\"\s}' READARR

          python3 update-versions/update-versions.py \
            --file applications/charts/prometheus/Chart.yaml \
            --replace '\s*?version:\s\"(.*)\"' PROMETHEUS

          python3 update-versions/update-versions.py \
            --file applications/charts/prometheus/values-node-b.yaml \
            --replace '\s*?proxy:\s{\sversion:\s\"(.*)\"\s}' OAUTH2PROXY

          python3 update-versions/update-versions.py \
            --file applications/charts/grafana/Chart.yaml \
            --replace '\s*?version:\s\"(.*)\"' GRAFANA

          python3 update-versions/update-versions.py \
            --file applications/charts/grafana/values-node-b.yaml \
            --replace '\s*?proxy:\s{\sversion:\s\"(.*)\"\s}' OAUTH2PROXY

          python3 update-versions/update-versions.py \
            --file applications/charts/loki/Chart.yaml \
            --replace '\s*?version:\s\"(.*)\"' LOKI

          python3 update-versions/update-versions.py \
            --file applications/charts/tautulli/values-node-b.yaml \
            --replace 'tautulli:\s{\sversion:\s\"(.*)\"\s}' TAUTULLI \
            --replace 'oauth2proxy:\s{\sversion:\s\"(.*)\"\s}' OAUTH2PROXY

          python3 update-versions/update-versions.py \
            --file applications/charts/overseerr/values-node-b.yaml \
            --replace 'overseerr:\s{\sversion:\s\"(.*)\"\s}' OVERSEERR \
            --replace 'oauth2proxy:\s{\sversion:\s\"(.*)\"\s}' OAUTH2PROXY

          python3 update-versions/update-versions.py \
            --file applications/charts/calibre/values-node-b.yaml \
            --replace 'calibre:\s{\sversion:\s\"(.*)\"\s}' CALIBRE \
            --replace 'calibreweb:\s{\sversion:\s\"(.*)\"\s}' CALIBREWEB \
            --replace 'oauth2proxy:\s{\sversion:\s\"(.*)\"\s}' OAUTH2PROXY

      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        with:
          path: applications
          commit-message: "chore(update): Update versions"
          branch: "chore/update-versions-${{ steps.date.outputs.date }}"
          delete-branch: true
          title: "chore: Update versions ${{ steps.date.outputs.date }}"
          reviewers: |
            sebastianhutter
