{{- if .Values.externalSecret.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # hardcoded for easier reference
  name: loki-gateway-basic-auth
spec:
  data:
  - remoteRef:
      key: hutter-cloud-loki-gateway-credentials
    secretKey: htpasswd
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        auth: {{ printf "'{{ .htpasswd }}'" }}
      engineVersion: v2
{{- end }}
