{{- if .Values.externalSecret.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # hardcoded for easier reference
  name: jenkins-auth0-client-id
spec:
  data:
  - remoteRef:
      key: hutter-cloud-service-jenkins-client-id
    secretKey: clientId
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: "secretText"
        annotations:
          jenkins.io/credentials-description : "client id  for auth0 oic integration, used by casc so its a secret text!"
      data:
        text: {{ printf "'{{ .clientId }}'" }}
        password: {{ printf "'{{ .clientSecret }}'" }}
      engineVersion: v2

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # hardcoded for easier reference
  name: jenkins-auth0-client-secret
spec:
  data:
  - remoteRef:
      key: hutter-cloud-service-jenkins-client-secret
    secretKey: clientSecret
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: "tsecretTextext"
        annotations:
          jenkins.io/credentials-description : "client secret for auth0 oic integration, used by casc so its a secret text!"
      data:
        text: {{ printf "'{{ .clientSecret }}'" }}
      engineVersion: v2
{{- end }}
