{{- if .Values.externalSecret.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # hardcoded for easier reference
  name: jenkins-auth0-client
  labels:
    jenkins.io/credentials-type: "usernamePassword"
  annotations:
    jenkins.io/credentials-description : "credential id and secret for auth0 oic integration"
spec:
  data:
  - remoteRef:
      key: hutter-cloud-service-jenkins-client-id
    secretKey: clientId
  - remoteRef:
      key: hutter-cloud-service-jenkins-client-secret
    secretKey: clientSecret
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        username: {{ printf "'{{ .clientId }}'" }}
        password: {{ printf "'{{ .clientSecret }}'" }}
      engineVersion: v2
{{- end }}
