{{- if .Values.externalSecret.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # hardcoded for easier reference
  name: jenkins-auth0-client
spec:
  data:
  - remoteRef:
      key: hutter-cloud-service-jenkins-client-id
    secretKey: clientId
  - remoteRef:
      key: hutter-cloud-service-jenkins-client-secret
    secretKey: clientSecret
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
    #   metadata:
    #     labels:
    #       jenkins.io/credentials-type: "usernamePassword"
    #     annotations:
    #       jenkins.io/credentials-description : "credential id and secret for auth0 oic integration"
      data:
        clientId: {{ printf "'{{ .clientId }}'" }}
        clientSecret: {{ printf "'{{ .clientSecret }}'" }}
      engineVersion: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # hardcoded for easier reference
  name: jenkins-iam-secrets-manager
spec:
  data:
  - remoteRef:
      key: hutter-cloud-secrets-manager-access-key-id
    secretKey: accessKeyId
  - remoteRef:
      key: hutter-cloud-secrets-manager-secret-access-key
    secretKey: secretAccessKey
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: ssm
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        accessKeyId: {{ printf "'{{ .accessKeyId }}'" }}
        secretAccessKey: {{ printf "'{{ .secretAccessKey }}'" }}
        defaultRegion: "eu-central-1"
      engineVersion: v2
{{- end }}
